server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka



spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: emailModule
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email/**
        - id: noteModule
          uri: lb://note-service
          predicates:
            - Path=/note/**
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/user/**